describe('Advertisement post modal', () => {
  it('add new advertisement', () => {
    const stub = cy.stub()
    cy.on('window:alert', stub)

    cy.visit('/advertisements')

    cy.get('[data-test="table-header-add"]').click()
    cy.get('[data-test="dialog-panel"]').should('be.visible')
    cy.get('#topicId').type('20% Скидка для ремонт', { force: true })
    cy.get('#addressids').click({ force: true })
    cy.get('#select-addressids-0').click()
    cy.get('#select-addressids-1').click()
    cy.get('#select-addressids-2').click()
    cy.get('#carids').click({ force: true })
    cy.get('#select-carids-0').click()
    cy.get('#select-carids-1').click()
    cy.get('#select-carids-2').click()
    cy.get('#serviceIds').click({ force: true })
    cy.get('#select-serviceIds-0').click()
    cy.get('#select-serviceIds-1').click()
    cy.get('#select-serviceIds-2').click()
    cy.get('#adserviceId').click({ force: true })
    cy.get('#select-adserviceId-1').click({ force: true })
    cy.get('#datepickerfrom').click({ force: true })
    cy.get(`#dp-menu-datepickerfrom [data-test="${new Date('2023-01-05 00:00:00')}"]`).click()
    cy.get('#datepickerto').click({ force: true })
    cy.get(`#dp-menu-datepickerto [data-test="${new Date('2023-01-06 00:00:00')}"]`).click()
    cy.get('#urlId').type('http://localhost:5173/ads', { force: true })
    cy.get('[data-test="file-input"]').selectFile('cypress/fixtures/profile.jpg', { force: true })
    cy.get('[data-test="video-upload"]').selectFile('cypress/fixtures/video.mp4', { force: true })
    cy.get('[data-test="ad-submit"]')
      .click()
      .then(() => {
        const payload = JSON.parse(stub.getCall(0).args[0])
        expect(payload).to.have.property('topic', '20% Скидка для ремонт')
        expect(payload).to.have.property('url', 'http://localhost:5173/ads')
      })
  })
})
